/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InputBytestream {
    'location': string;
    'mediaType': string;
    'mtime': string;
    'name': string;
    'size': number;
    'uuid': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLInputBytestreamElement extends Components.InputBytestream, HTMLStencilElement {}
  var HTMLInputBytestreamElement: {
    prototype: HTMLInputBytestreamElement;
    new (): HTMLInputBytestreamElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'input-bytestream': HTMLInputBytestreamElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface InputBytestream extends JSXBase.HTMLAttributes<HTMLInputBytestreamElement> {
    'location': string;
    'mediaType'?: string;
    'mtime'?: string;
    'name': string;
    'size'?: number;
    'uuid': string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'input-bytestream': InputBytestream;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


