/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ButtonAuth {
    'classes': string;
    'disabled': boolean;
    'formId': string;
    'href': string;
  }
  interface InputBytestream {
    'checked': boolean;
    'classes': string;
    'location': string;
    'mediaType': string;
    'mtime': string;
    'name': string;
    'onChange': (event: object) => void;
    'size': number;
    'uuid': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLButtonAuthElement extends Components.ButtonAuth, HTMLStencilElement {}
  const HTMLButtonAuthElement: {
    prototype: HTMLButtonAuthElement;
    new (): HTMLButtonAuthElement;
  };

  interface HTMLInputBytestreamElement extends Components.InputBytestream, HTMLStencilElement {}
  const HTMLInputBytestreamElement: {
    prototype: HTMLInputBytestreamElement;
    new (): HTMLInputBytestreamElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'button-auth': HTMLButtonAuthElement;
    'input-bytestream': HTMLInputBytestreamElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface ButtonAuth {
    'classes'?: string;
    'disabled'?: boolean;
    'formId'?: string;
    'href'?: string;
  }
  interface InputBytestream {
    'checked'?: boolean;
    'classes'?: string;
    'location'?: string;
    'mediaType'?: string;
    'mtime'?: string;
    'name': string;
    'onChange'?: (event: object) => void;
    'size'?: number;
    'uuid'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'button-auth': ButtonAuth;
    'input-bytestream': InputBytestream;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'button-auth': LocalJSX.ButtonAuth & JSXBase.HTMLAttributes<HTMLButtonAuthElement>;
      'input-bytestream': LocalJSX.InputBytestream & JSXBase.HTMLAttributes<HTMLInputBytestreamElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


